plugins {
	id 'java'
	id 'maven-publish'
	id 'net.neoforged.moddev' version '2.0.143'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = "${project.archives_base_name}-neoforge-${project.minecraft_version}"
}

neoForge {
	version = project.neo_version

	validateAccessTransformers = true

	runs {
		client {
			client()
		}
		server {
			server()
		}
	}

	mods {
		culturalcreators {
			sourceSet sourceSets.main
		}
	}
}

processResources {
	def expandProps = [
			"version"                : project.version,
			"minecraft_version_range": project.minecraft_version_range,
			"neo_version_range"      : project.neo_version_range,
			"loader_version_range"   : project.loader_version_range
	]

	inputs.properties(expandProps)

	filesMatching("META-INF/neoforge.mods.toml") {
		expand expandProps
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
