modLoader="javafml"
loaderVersion="${loader_version_range}"
license="CC0-1.0"
issueTrackerURL="https://github.com/Flomik10002/CulturalCreatorsFabric/issues"

[[mods]]
modId="culturalcreators"
version="${version}"
displayName="Cultural Creators"
displayURL="https://github.com/Flomik10002/CulturalCreatorsFabric"
logoFile="assets/culturalcreators/icon.png"
authors="Flomik"
description='''
Making automation between Culturals Delight and Create
'''

[[dependencies.culturalcreators]]
	modId="neoforge"
	type="required"
	versionRange="${neo_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.culturalcreators]]
	modId="minecraft"
	type="required"
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.culturalcreators]]
	modId="create"
	type="optional"
	versionRange="*"
	ordering="AFTER"
	side="BOTH"

[[dependencies.culturalcreators]]
	modId="farmersdelight"
	type="optional"
	versionRange="*"
	ordering="AFTER"
	side="BOTH"

[[dependencies.culturalcreators]]
	modId="culturaldelights"
	type="optional"
	versionRange="*"
	ordering="AFTER"
	side="BOTH"

[[dependencies.culturalcreators]]
	modId="delightfulcreators"
	type="optional"
	versionRange="*"
	ordering="AFTER"
	side="BOTH"
